### ISSUE TITLE
handle other html tags ?

### ISSUE THREAD

**Issue by DJafari** [fourlastor/dante#3]
thanks for your great library
do you plan to support another html tags, such as `img`, `table` ?

**Comment by fourlastor** [comment]
Hi!

For `table`: it's a bit complicated, it depends on if you can render something like that in a `Spannable`. I never looked into it but I agree it would be a great addition.

For `img`: technically it's "just" a matter of using `ImageSpan`, but I'd have to modify a bit the html parser (right now I ignore the attributes, could start supporting only `src`), I'll try to do something this week and come back to you as soon as I know :)

**Comment by DJafari** [comment]
ok thanks
it's to be good that `br` tag is supported too :-)

**Comment by rock3r** [comment]
Tables might be a bit out of scope of what `Span`s are meant to do. `ImageSpan` must be used with great care too, as you usually have little control over how that ends up in the text run. I think the point is that this library is not meant to replace webview but rather to render simple markup-enhanced text runs.

**Comment by fourlastor** [comment]
<img src="https://cloud.githubusercontent.com/assets/1263058/23238737/5abc1b86-f95b-11e6-85a1-3da3aa6aedc3.png" width="300" />

I didn't forget :tongue: the results aren't _yet_ great but it's getting there!

**Comment by fourlastor** [comment]
See #5

**Comment by fourlastor** [comment]
@DJafari image tags are now supported! :tada: update dante to `0.1.0`! :)
